### ISSUE TITLE
Drinking Bug

### ISSUE THREAD

**Issue by KXIIIS** [Globox1997/AppleZ#1]
Hey mate, when I drink from a stack of apple juice, it consumes the entire stack rather than just one bottle. I'm on version Fabric 0.8.2+build.194-1.15.2, AppleZ 1.7. Thanks for all your hard work :)

**Comment by Globox1997** [comment]
thanks for the info, I will fix it

**Comment by KXIIIS** [comment]
Thanks sm :)

**Comment by Globox1997** [comment]
fixed it
